#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#event_add:
#  path: /back/add
#  controller: App\Controller\EventController::addEvent
#  methods: [GET, POST]

event_pdf:
    path: /events/pdf
    controller: App\Controller\EventController::pdf


event_pdf_participant:
    path: /participant/pdf
    controller: App\Controller\ParticipantController::pdfListeParticipant